<a href="https://colab.research.google.com/github/2lory/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Assignment 3 : Matrices

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\ 
C = \left\{
    \begin{array}\
        w - 2x + 3y - 4z \\ 
        3w - x -2y + z \\
        2w - x + 3y - 2z
    \end{array}
\right. \\ $$

A = \begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B = \begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & {2}\end{bmatrix}  
C = \begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & {-2}\end{bmatrix} \\



## Declaring Matrices

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [7]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nBank:\t{matrix.ndim}\n')

In [10]:
## Declaring a 2 x 2 matrix
A = np.array([
              [4, 8],
              [9, 6]
])
describe_mat(A)


Matrix:
[[4 8]
 [9 6]]

Shape:	(2, 2)
Bank:	2



In [12]:
G = np.array([
    [2,4,6],
    [6,6,8]
])
describe_mat(G)


Matrix:
[[2 4 6]
 [6 6 8]]

Shape:	(2, 3)
Bank:	2



In [15]:
B = np.array([
    [9, 3],
    [2,6],
    [0, 0]
])
describe_mat(B)


Matrix:
[[ 9  3]
 [ 2 64]
 [ 0  0]]

Shape:	(3, 2)
Bank:	2



In [16]:
H = np.array([2,4,6,8])
describe_mat(H)


Matrix:
[2 4 6 8]

Shape:	(4,)
Bank:	1



# Categorizing Matrices

## Rows and Column Matrices

In [17]:
## Declaring a Row Matrix
rowmatrix1D = np.array([
    2, 4, 6, -8
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [2,4,6, -8]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 2  4  6 -8]

Shape:	(4,)
Bank:	1

Matrix:
[[ 2  4  6 -8]]

Shape:	(1, 4)
Bank:	2



In [18]:
## Declaring a Column Matrix
col_mat = np.array([
    [3],
    [6],
    [8]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[3]
 [6]
 [8]]

Shape:	(3, 1)
Bank:	2



### Square Matrices

In [19]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [21]:
square_mat = np.array([
    [3,6,9],
    [4,4,10],
    [4,0,3]
])

non_square_mat = np.array([
    [2,5,7],
    [6,6,9]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[ 3  6  9]
 [ 4  4 10]
 [ 4  0  3]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 5 7]
 [6 6 9]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### Null Matrix

In [22]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [25]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


### Zero Matrix

In [28]:
zero_mat_row = np.zeros((3,4))
zero_mat_sqr = np.zeros((4,4))
zero_mat_rct = np.zeros((5,4))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Ones Matrix

In [29]:
ones_mat_row = np.ones((3,4))
ones_mat_sqr = np.ones((4,4))
ones_mat_rct = np.ones((5,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Diagonal Matrix

In [33]:
np.array([
    [4,2,2],
    [2,6,2],
    [2,2,8]
])


array([[4, 2, 2],
       [2, 6, 2],
       [2, 2, 8]])

In [32]:
d = np.diag([2,3,5,7])
#d.shape[0] == d.shape[1]
d


array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

### Identity Matrix

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(20)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [40]:
F = np.array([
       [2, 4, -6, 8],
       [2, 4, -6, 8],
       [2, 4, -6, 8],
       [2, 4, -6, 8],     
])
np.triu(F)

array([[ 2,  4, -6,  8],
       [ 0,  4, -6,  8],
       [ 0,  0, -6,  8],
       [ 0,  0,  0,  8]])

### Lower Triangular Matrix

In [44]:
np.tril(F)

array([[ 2,  0,  0,  0],
       [ 2,  4,  0,  0],
       [ 2,  4, -6,  0],
       [ 2,  4, -6,  8]])

In [45]:
np.array([
          [2,1,1],
          [6,4,1],
          [9,7,6],
])

array([[2, 1, 1],
       [6, 4, 1],
       [9, 7, 6]])