<a href="https://colab.research.google.com/github/2lory/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Transposition

$$A = \begin{bmatrix} 2 & 5 & 8\\6 & 4 &1 \\ 1 & -5 & 9\end{bmatrix} $$


$$ A^T = \begin{bmatrix} 2 & 6 & 1\\5 & 4 &-5 \\ 8 & 1 & 9\end{bmatrix}$$

$$B = \begin{bmatrix} -3 & 1 & 4\\9 & 5 &6 \\ 10 & -2 & 7\end{bmatrix} $$

$$ B^T = \begin{bmatrix} -3 & 9 & 10\\1 & 5 &-2 \\ 4 & 6 & 7\end{bmatrix}$$

In [7]:
A = np.array([
     [2, 5, 8],
     [6, 4, 1],
     [1, -5, 9]
])
A

array([[ 2,  5,  8],
       [ 6,  4,  1],
       [ 1, -5,  9]])

In [8]:
AT1 = np.transpose(A)
AT1

array([[ 2,  6,  1],
       [ 5,  4, -5],
       [ 8,  1,  9]])

In [9]:
AT2 = A.T
AT2

array([[ 2,  6,  1],
       [ 5,  4, -5],
       [ 8,  1,  9]])

In [10]:
np.array_equiv(AT1, AT2)

True

In [14]:
B = np.array([
    [-3, 1, 4],
    [9, 5, 6],
    [10, -2, 7]
])
B.shape

(3, 3)

In [15]:
np.transpose(B).shape

(3, 3)

In [16]:
B.T.shape

(3, 3)

In [17]:
X = np.array([
    [2,4],
    [3,9]
])
Y = np.array([
    [7,-5],
    [6,6]
])

In [18]:
np.array_equiv(X, Y)

False

In [19]:
np.dot(X,Y)

array([[38, 14],
       [75, 39]])

In [20]:
X.dot(Y)

array([[38, 14],
       [75, 39]])

In [21]:
X @ Y

array([[38, 14],
       [75, 39]])

In [22]:
np.matmul(X,Y)

array([[38, 14],
       [75, 39]])

In [24]:
A = np.array([
    [6, 9],
    [0, -4],
    [8, 11]
])
B = np.array([
    [0,0],
    [9,6],
    [-4,-5]
])
C = np.array([
    [9,0,3],
    [2,4,9]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [25]:
A @ C

array([[ 72,  36,  99],
       [ -8, -16, -36],
       [ 94,  44, 123]])

In [26]:
B @ C

array([[  0,   0,   0],
       [ 93,  24,  81],
       [-46, -20, -57]])

In [27]:
A @ B.T

array([[  0, 108, -69],
       [  0, -24,  20],
       [  0, 138, -87]])

In [28]:
A = np.array([
    [2, 8],
    [-7, 5]
])
np.linalg.det(A)

65.99999999999997

In [29]:
B = np.array([
    [-5, 4 , 8],
    [6, 0, 1],
    [-3, -3, 2]
])
np.linalg.det(B)

-218.99999999999983

In [30]:
P = np.array([
              [-1, 7, 5],
              [3, 9, 0],
              [2, 4, 10]
])
Q = np.linalg.inv(P)
Q

array([[-0.27272727,  0.15151515,  0.13636364],
       [ 0.09090909,  0.06060606, -0.04545455],
       [ 0.01818182, -0.05454545,  0.09090909]])

In [31]:
P @ Q

array([[ 1.00000000e+00, -6.93889390e-18, -8.32667268e-17],
       [ 8.32667268e-17,  1.00000000e+00,  6.93889390e-18],
       [ 7.63278329e-17, -1.38777878e-17,  1.00000000e+00]])